credentials:
  usernames:
    santi:
      email: santimaldonado2@gmail.com
      name: Santiago Jose Maldonado
      password: '$2b$12$D539WhyI6vg4fFAaSaVQ3ew5pbQMU/5dtYVYm06kunovxXOVZbRva'
    smaldonado:
      email: smaldonado@mznetworks.com
      name: Ing Sebastian Eduardo Maldonado
      password: '$2b$12$D539WhyI6vg4fFAaSaVQ3ew5pbQMU/5dtYVYm06kunovxXOVZbRva'
    jfzalazar:
      email: jfzalazar@mznetworks.com
      name: Ing Juan Facundo Salazar
      password: '$2b$12$D539WhyI6vg4fFAaSaVQ3ew5pbQMU/5dtYVYm06kunovxXOVZbRva'
cookie:
  expiry_days: 30
  key: hzios # Must be string
  name: hzios_cookie
preauthorized:
  emails:
  - santimaldonado2@gmail.com
