credentials:
  usernames:
    santi:
      email: santimaldonado2@gmail.com
      name: Santiago Jose Maldonado
      password: '$2b$12$JXci/Q31ZYIEjUgC.ZgYSuxh8gfeeC3JbR6o.vE5z9UmSciDiEfZO'
    smaldonado:
      email: smaldonado@mznetworks.com
      name: Ing Sebastian Eduardo Maldonado
      password: '$2b$12$JXci/Q31ZYIEjUgC.ZgYSuxh8gfeeC3JbR6o.vE5z9UmSciDiEfZO'
    jfzalazar:
      email: jfzalazar@mznetworks.com
      name: Ing Juan Facundo Salazar
      password: '$2b$12$JXci/Q31ZYIEjUgC.ZgYSuxh8gfeeC3JbR6o.vE5z9UmSciDiEfZO'
cookie:
  expiry_days: 30
  key: hzios # Must be string
  name: hzios_cookie
preauthorized:
  emails:
  - santimaldonado2@gmail.com
